### PR TITLE
Add support for the latest CDS SDK (.NET Core)

### PR DESCRIPTION
**Pull request by michal-turzynski**
# Description

This pull request contains the results of my experiments with the FakeXrmEasy and custom .NET Core projects that are using the latest CDS SDK:

[Microsoft.Powerplatform.Cds.Client](https://www.nuget.org/packages/Microsoft.Powerplatform.Cds.Client)

[Microsoft.Powerplatform.Cds.Client.Dynamics](https://www.nuget.org/packages/Microsoft.Powerplatform.Cds.Client.Dynamics)

[Microsoft.Dynamics.Sdk.Messages](https://www.nuget.org/packages/Microsoft.Dynamics.Sdk.Messages)

Please also note that those Nuget packages are still in prerelease state.

# More details

Unfortunately, I wasn't able to re-use the shared Visual Studio projects as the above CDS SDKs don't support D365/CDS plugins and custom code activities. 

# How Has This Been Tested?

I copied the FakeXrmEasy.Tests project and unit tests to validate my changes.

Additionally, I published an Azure Functions App  code that could be used to test it:
[https://github.com/michal-turzynski/az-functions-dotnetcore-powerplatform-sample](https://github.com/michal-turzynski/az-functions-dotnetcore-powerplatform-sample)

The app is on .NET Core 3.1 and can be run on Linux based environments.

### CODE REVIEW

**Comment by jordimontana82** [comment]
Hi @michal-turzynski ,

Thanks a mill for your PR... I had a version .net core running in a local branch too, which didn't push yet since I'm doing massive refactorings to it, potentially splitting projects into smaller nuget packages / repos for easier maintenance since this repo is getting too big :).

That's why I won't merge this one yet

If you don't mind, I'll review

**Comment by michal-turzynski** [comment]
> Hi @michal-turzynski ,
> 
> Thanks a mill for your PR... I had a version .net core running in a local branch too, which didn't push yet since I'm doing massive refactorings to it, potentially splitting projects into smaller nuget packages / repos for easier maintenance since this repo is getting too big :).
> 
> That's why I won't merge this one yet
> 
> If you don't mind, I'll review this PR as soon as the local branch is pushed.

@jordimontana82 - Absolutely, I completely understand. Good luck and if you need some help, feel free to give me a shout. Big fan of your project btw!

**Comment by jordimontana82** [comment]
No worries, btw I just saw this into a clone of FakeXrmEasy into a separate repo... I guess this is just a mistake since the only thing MIT is asking for is to retain copyright notices? :)

https://github.com/michal-turzynski/FakeCdsEasy/blob/master/LICENSE#L3

**Comment by michal-turzynski** [comment]
> No worries, btw I just saw this into a clone of FakeXrmEasy into a separate repo... I guess this is just a mistake since the only thing MIT is asking for is to retain copyright notices? :)
> 
> https://github.com/michal-turzynski/FakeCdsEasy/blob/master/LICENSE#L3

That was just experimental/temp repo where I tested the changes. It's already deleted. Thanks!

**Comment by jordimontana82** [comment]
No prob, thx @michal-turzynski !

**Comment by mathiasbl** [comment]
@jordimontana82 I was wondering I u had a working version for .net core? I could also offer to help test it.

**Comment by michal-turzynski** [comment]
Same here :)

**Comment by jordimontana82** [comment]
@mathiasbl @michal-turzynski  I do, however it has significant changes compared to v1.x and the repository has been reorganised into several smaller repos / nuget packages. I'll publish it eventually, but here's a roadmap for it I demoed at the Malaysia user group (https://github.com/DynamicsValue/malaysia-bizappug-intro-to-fake-xrm-easy), 

Will publish it at the dynamicsvalue org level (http://github.com/dynamicsvalue) and post an update in this repo, which will be used mainly to maintain / monitor 1.x changes only.

Closing this PR cause it's way behind those changes :)

**Pull request closed without merging**
