### PR TITLE
Return a clearer ErrorMessage for Invalid EntityFilter values

### PR DESCRIPTION
**Pull request by TheFehr**
I stumbled upon this Error today while using FakeXrmEasy to unit test a plugin. Took me some time to figure out where exactly the error came from and what it meant. 
This is just an idea for what to return, it'd just be good for the receiver of the error to need less time to figure out what went wrong.

### CODE REVIEW

**Comment by TheFehr** [comment]
@jordimontana82 can I do anything more to get this PR merged? Thanks for the quick answer.

**Comment by jordimontana82** [comment]
Thanks @TheFehr !

No that's fine, I was just reviewing PRs in order that's all, but given this is just a wording change, I'll merge it straight away thanks.

**Comment by jordimontana82** [comment]
This was pushed to v1.57.0

**Comment by TheFehr** [comment]
Thanks for the merge

**Pull request merged**
