### PR TITLE
Added Bi-Directional support for Associate message

### PR DESCRIPTION
**Pull request by amolotkov**

### CODE REVIEW

**Comment by jordimontana82** [comment]
Hi @amolotkov!

How are you?

I think we were working in parallel on the same file and hence this conflict. What I introduced was that whenever associate request is called, it expects the parameters in the same order they were declared in the fake relationship, whereas your change makes it possible to use one or the other.

I've come across issues where the order was important... can't remember the details now so maybe I'll play with this a little bit against a real CRM instance :)

**Comment by amolotkov** [comment]
Sure, :) crm definitely doesn't care about the order, but rules on the
logical names of the parameters. The other thing I'm planning to add in the
next couple of days is exexcutefetch request - basic implementation that's
will return result of fetchquery as an XML. Let me know if that's in works
as well :-)

**Comment by jordimontana82** [comment]
Yeah, definetely remember something weird when 2 N:N relationships were created between the 2 same pair of entities ... something funny with the associated views.... Can't remember what exactly but will double check :) 

No short plan on implementing that executefetch message but because FakeXrmEasy already runs FetchXml queries, it shouldn't be a big deal. Would be awesome if you could add it! ;)

**Comment by jordimontana82** [comment]
That's merged now @amolotkov 

Just added 2 queries to make sure the records you wanna associate actually exist.

**Comment by amolotkov** [comment]
Thank you

**Comment by jordimontana82** [comment]
@amolotkov We could do the same thing for the Disassociate message executor as well.

Would you like to look into it?

**Pull request merged**
