### PR TITLE
Add saving DateTime attributes in UTC

### PR DESCRIPTION
**Pull request by Kraviecc**
Hi,

I've added converting DateTime attributes to UTC kind, just like in real CRM. #300

### CODE REVIEW

**Comment by jordimontana82** [comment]
Thx so much for this.... now, this will introduce breaking changes for almost all my existing tests using dates :D 

Would you think is worth it moving it to a separate branch where we could include other breaking stuff?

**Comment by Kraviecc** [comment]
What's going to happen with this branch in the future? These breaking changes should be merged into master in spite of all - maybe not now but certainly ever :).
Another way would be to, as you said, keep for a while this branch and then make major release (ie. 2.x.x). Or maybe different, in-code solution, but I have no ideas for this in the moment.

**Comment by jordimontana82** [comment]
I was thinking of a dev branch i.e. v2.0.0 which will be merged at some point into master yep.

Or maybe if it is not a big deal it can be a new minor version, in which case I'll merge it directly into master

**Comment by Kraviecc** [comment]
The idea of dev 2.0.0 branch sounds good for me. This is going to be a container for breaking changes which will be merged into master in the right time :)

Is there anything I should do with this pr? Can't create new one to branch which doesn't exist yet.

**Comment by jordimontana82** [comment]
Gonna merge it into master instead and push it to the next minor version. 

It's not a huge breaking change (i.e. no breaking changes to method calls / types / etc.  ) so people can still use the previous version while accomodating these changes :)

**Comment by jordimontana82** [comment]
That's in 1.42.0 now

**Pull request merged**
