### PR TITLE
Additional Fix for issue 114. Crm contxt generated using Xrm.Client i…

### PR DESCRIPTION
**Pull request by amolotkov**
…s using Microsoft.Xrm.Client.CrmEntityReference instead of EntityRefernce object. Fixed casting issue.

### CODE REVIEW

**Comment by jordimontana82** [comment]
Hi @amolotkov 

Quick question... how did you generate the Typed Entities? Cause I also use CRM 2011 and got entity references generated as EntityReference, not CrmEntityReference?

**Comment by amolotkov** [comment]
Use /codeCustomization:"Microsoft.Xrm.Client.CodeGeneration.CodeCustomization, Microsoft.Xrm.Client.CodeGeneration" key  with crmsvcutil

crmsvcutil.exe /codeCustomization:"Microsoft.Xrm.Client.CodeGeneration.CodeCustomization, Microsoft.Xrm.Client.CodeGeneration" ....

**Comment by jordimontana82** [comment]
Mmm I am wondering... if would be just enough to make your CrmEntityReference inherit from EntityReference in your proxytypes, and that should be picked up by the framework?  Could you just try that or post how are you generating your custom code so that I can play with it?

**Comment by amolotkov** [comment]
That's wouldn't work, the code is generated by crmSvcUtil. In order to get it generate that way t you would need to specify /codeCustomization:"Microsoft.Xrm.Client.CodeGeneration.CodeCustomization, Microsoft.Xrm.Client.CodeGeneration" key in the command line.

Also, there are couple of things. the framework was handling that model perfectly fine prior version 1.19.2, and the second part - that might be useful . Looks like the instance of the CrmEntityReffrence can be implicitly converted to EntityReference .. 
For instance if you do something like 
EntityReference s = new CrmEntityRefernce();
then s.GetType()  will return EntityReference and  the s is EntityReference  will return true, 
But 
CrmEntityRefernce s = new CrmEntityRefernce();
then s.GetType()  will return CrmEntityRefernce and  the s is EntityRefernce  will return false,  but the (EntityRefernce)s is EntityRefernce  will return true,

**Comment by jordimontana82** [comment]
Yep, since that version the framework is checking that types should match to overcome issue #108 , where it was trying to guess types based on the values from the right hand side of the expression, rather than checking the actual type from the early bound entity.   

I'd like to keep it simple and just use EntityReference classes or classes inheriting from them, cause, in the end, these classes need to be serialised as EntityReferences when sent to CRM anyway...   otherwise one might generate such classes as CrmEntityReference, or give any other class name, which would make the framework difficult to maintain.

**Comment by amolotkov** [comment]
But that CrmEntityreference is generated buy the SDK code, and as I
mentioned there is no additional code required to cast CrmEntityRefernce to
EntityReference, microsoft covered that, so you can easily convert the
 actual CrmEntityRefercne values into EntityRefernce inside  the data, but
unfortunately the DataModel definition that is generated defines the values
as CrmEntityReference.

**Comment by jordimontana82** [comment]
Sorry just had a chance to look into this... 

That's interesting... I always used a different code customization parameter which always generated EntityReference classes just by following the samples from the SDK, so they don't generate CrmEntityReference classes, that's for sure, when running something like:

/codecustomization:"Microsoft.Crm.Sdk.Samples.CodeCustomizationService, GeneratePicklistEnums"

I'm wondering, any specific reason to run it with the Xrm.Client namespace as you do? To have some entity extensions maybe?

**Comment by amolotkov** [comment]
Not sure either, I've inherited that project :) and unfortunately it's too
big to change the way proxy generated., the main difference besides
crmentityrefernce class is the option set values defined as nullable int.
My guess that implementation done for backward compatibility to original
xrm.sdk implementation that was used back in crm 4.0 time.

**Pull request merged**
