### PR TITLE
Added method that allows to execute plugin with configuration parameters

### PR DESCRIPTION
**Pull request by DigitalFlow**
Hey Jordi,

I implemented the method for executing a plugin with configuration parameters.

Kind Regards,
DigitalFlow

### CODE REVIEW

**Comment by jordimontana82** [comment]
Hi @DigitalFlow 

That's great! Thanks for the contribution ... I'll review it as soon as I have a chance.

Greetings from Wexford :)

**Comment by jordimontana82** [comment]
Hi @DigitalFlow !

I've merged your changes and made some slightly changes.

I've moved the MessageName, UserId, and InitiatingUserId properties from the XrmFakedContext to a new class XrmFakedPluginExecutionContext.

This is because purpose of the XrmFakedContext was to just hold the entities in memory, plus the place to go get fake objects that work against that context (like an organization service, plugin context, a code activity context), so having those properties in the XrmFakedContext seemed like we were mixing 2 different things, the In Memory  context and the IPluginExecutionContext.

So, I refactored those attributes to the new XrmFakedPluginExecutionContext class, which we could pass to the ExecutePlugin method as well, to pass other properties from the context we might need (like a SecondaryEntityName in the Associate message, for example).

The ExecutePlugin will use a default XrmFakedPluginExecutionContext if non was passed as well. The purpose is, in order to keep unit tests as simple as possible, not to enforce to pass a context, but only to pass it when the plugin needs it (i.e., there will be plugins where you don't care about the message name, or userid or initiating user id).

Hope this makes sense and thanks a mill for the contribution! :)

**Comment by jordimontana82** [comment]
Actually, the method: ExecutePluginWith<ConfigurationPlugin>(inputParams, new ParameterCollection(),
 new EntityImageCollection(), new EntityImageCollection(), unsecureConfiguration, secureConfiguration); could be possibly overloaded with a new method like:

ExecutePluginWith<ConfigurationPlugin>(XrmFakedPluginExecutionContext plugCtx, unsecureConfiguration, secureConfiguration) to be consistent and keep the method signature even more simple.

What do you think?

**Comment by DigitalFlow** [comment]
Sounds reasonable, this method certainly has a long parameter list right now.
Should I implement or do you want to?

**Comment by jordimontana82** [comment]
Sorry... I've just been very busy lately.... I'll implement it, it is just a single method, it would be quicker than just creating a pull request just for that simple thing... :)

**Comment by DigitalFlow** [comment]
All right, sounds great :+1:

**Pull request merged**
