### PR TITLE
Switched to FAKE

### PR DESCRIPTION
**Pull request by DigitalFlow**
Hey Jordi,

I implemented an automated build using F# - FAKE.
Please have a look at it, I hope you'll like it.
This build already builds everything, runs the xunit tests and creates the NuGet packages.
Publishing those NuGet packages automatically is also possible.
Unfortunately the 2013, 2015 and 2016 tests have issues with two test cases and fail, maybe you know why.
To run a build, just execute 01_boot_and_build.bat.

Kind Regards,
Florian

### CODE REVIEW

**Comment by jordimontana82** [comment]
Super! :+1: 

I owe you a couple of beers now :) 

Which tests aren't passing? The [CI](https://ci.appveyor.com/project/Jordi/fake-xrm-easy/build/1.9.0.43) build for this PR seems fine?

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

the build passes, because it still runs as always.
For the build to run the FAKE build, it simply needs to call "01_boot_and_build.bat", that's all.
If you pull this PR and change the "Test" Target to look like this:
``` FSharp
Target "Test" (fun _ ->
    !! (testDir @@ "\**\FakeXrmEasy.Tests*.dll")
      |> xUnit (fun p -> { p with HtmlOutputPath = Some (testDir @@ "xunit.html") })
)
```
then all tests will be run and you see the following failures for 2013, 2015 and 2016:

```
When_doing_a_join_with_filter_then_can_filter_by_the_joined_entity_attributes [FAIL]
   Assert.True() Failure
   Stack Trace:
      bei FakeXrmEasy.Tests.FakeContextTestLinqQueries.When_doing_a_join_with_filter_then_can_filter_by_the_joined_entity_attributes() in C:\Users\fkroener\Entwicklung\FakeXrmEasy\FakeXrmEasy.Tests.Shared\FakeContextTests\LinqTests\FakeContextTestLinqQueries.cs:Zeile 842.
```
and
```
FakeXrmEasy.Tests.FakeContextTests.LinqTests.EqualityWithDifferentDataTypesTests.When_executing_a_linq_query_with_equals_between_2_activityparties_result_is_returned [FAIL]
   Assert.True() Failure
   Stack Trace:
      bei FakeXrmEasy.Tests.FakeContextTests.LinqTests.EqualityWithDifferentDataTypesTests.When_executing_a_linq_query_with_equals_between_2_activityparties_result_is_returned() in C:\Users\fkroener\Entwicklung\FakeXrmEasy\FakeXrmEasy.Tests.Shared\FakeContextTests\LinqTests\EqualityWithDifferentDataTypesTests.cs:Zeile 0.
```

Kind Regards,
Florian

**Comment by jordimontana82** [comment]
Hey @DigitalFlow ,

Finally had some time today to look at this.

It wasn't building because the framework requires conditional compilation symbols which I added to your amazing FAKE script :+1: 

I also added some config to publish the NuGet packages.

**Comment by DigitalFlow** [comment]
Great! :+1: 
I'm glad that you like it.

**Pull request merged**
