### PR TITLE
Added implementation for associate / disassociate message and tests

### PR DESCRIPTION
**Pull request by DigitalFlow**
Hey @jordimontana82,

I added an implementation for the associate and for the disassociate message.
There are also some tests included.
There might be some rough edges to it, but its working good so far and the tests are passing.

Kind Regards

### CODE REVIEW

**Comment by DigitalFlow** [comment]
Just saw that there might be some changes needed.
MS examples state "systemuserroles_association" as relationship for example. There might be a differentiation missing.

**Comment by jordimontana82** [comment]
Great! :+1: 

I'll have a look

**Comment by jordimontana82** [comment]
Looks good to me. 
You mean MS examples use this specific format "systemuserroles_association" as opposed to just ""systemuserroles" you added? That's ok I suppose because you can edit the relationship name in CRM too.

**Comment by DigitalFlow** [comment]
Hey @jordimontana82,

I use VS 2015, so that's ok for me.

**Comment by jordimontana82** [comment]
Great

**Pull request merged**
