### PR TITLE
Allow hybrid entities, from generated code mixed with dynamic

### PR DESCRIPTION
**Pull request by eNeRGy164**
- Relaxed the engine a bit to use generated metatdata when the type is present, otherwise handle as we handle dynamic types
- Add a separate project that has a small generated file, this should allow testing of generated code with not all system entities present

### CODE REVIEW

**Comment by jordimontana82** [comment]
Hi Michael!

I'd rather prefer to keep the early bound / late bound behavior as it is. It think it really should enforce to have all the early bound classes and complain whenever no entities are found (like sdk messagins steps), 
We do use that as part of our CI pipeline.

I'll submit a change to soon enable / disable puglin pipelines via config.

**Comment by eNeRGy164** [comment]
I don't really like config settings to globally change the behavior. This introduces state outside the unit test that can influence the outcome.
For that I rather have a Boolean property on the context that is false by default. But can be set to true on a unit test basis. With setting it implicitly to true when registering a plugin.

**Comment by jordimontana82** [comment]
@eNeRGy164  just reading this after I implemented that exact thing.... telepathy? :D

**Comment by jordimontana82** [comment]
So no need to have this PR then...

Issue was that in 1.34.0 every crud operation was executing plugin steps so it turned every unit test into a kind of integration test.

Now it will be defaulted to false in the constructor, and we'll only have to enable the pipeline simulation for simulating e2e tests.

**Pull request closed without merging**
