### PR TITLE
include primary key when joining attributes

### PR DESCRIPTION
**Pull request by rbec**
#64 is still broken. The problem is JoinAttributes does not include the primary id key. I have added 

`e[alias + "." + alias + "id"] = new AliasedValue(alias, alias + "id", otherEntity.Id);`

in 2 places and also added test cases.

### CODE REVIEW

**Comment by jordimontana82** [comment]
Thx @rbec 

Issue really is that when using dynamic entities the primary key is not populated when you assign the Id property.  This is not the same for early bound types, because then the Id property also assigns the underlying primary key.

In the commit I [slightly changed your unit test](https://github.com/jordimontana82/fake-xrm-easy/blob/c0cbe5437918d78691c69795b960a81467b9b469/FakeXrmEasy.Tests.Shared/FakeContextTests/TranslateQueryExpressionTests/FakeContextTestTranslateQueryExpression.cs#L695-L695) to include those and it was passing with that.

**Comment by rbec** [comment]
Thanks, that makes sense.
So would it be appropriate to do a check in XrmFakedContext.Initialize for the presence of the id field and add it if missing? This would make the behavior more in line with the real OrganizationService.

**Comment by jordimontana82** [comment]
Agree. :+1: 

It is doing it for early bound types already. We could do it for dynamic entities also checking that entityname + "id" should attribute exist.   Is that always the case though? I was wondering if it is possible to create an entity in CRM where the primary key doesn't follow that pattern...

**Comment by rbec** [comment]
I've just asked my colleagues who know more about this than I do and the consensus is that they always follow that pattern because the key fields are auto generated by CRM.

**Comment by jordimontana82** [comment]
Hi @rbec ,

I've made a small change which is available on latest version now. It will default the primary key from the Id property for dynamic entities.

**Comment by rbec** [comment]
Thank you

**Pull request closed without merging**
