### PR TITLE
Use the lowest possible dependency to increase compatibility in the field.

### PR DESCRIPTION
**Pull request by eNeRGy164**
By using the lowest version possible, we increase the number of supported version and reduce the forced upgrade if people are using older versions of NuGet packages.
This still leaves a gap, most noticeable for 8.0 which is not covered at the moment.

Also added the `allowedVersions` attribute in the `packages.config` to prevent people from accidentally upgrading to an out-of-range version.

This is response to #219

### CODE REVIEW

**Comment by jordimontana82** [comment]
Hi Micheal,
Thanks a mill for this PR.  What do you mean by the forced upgrade? For instance if they have project referenced in the unit test project that has a reference to an older SDK version? For that purpose one could add binding redirects in the app.config.

**Comment by eNeRGy164** [comment]
When my project uses NuGet package Microsoft.CrmSdk.XrmTooling.CoreAssembly version 8.2.0.2, and so my test project uses 8.2.0.2, installing FakeXrmEasy.365 will forcefully upgrade that NuGet package to 8.2.0.4 because it requires the version to be 8.2.0.4 or higher. 
Which will make me test against different assemblies then my project is build.

I think it's not done that libraries (/frameworks) are requiring higher versions of dependencies when that's not needed.

Therefore I think it's better to require only the major/minor version (e.g. 8.2) and not the revision itself. Leaving it to the user to decide which version they want to run against. Making upgrade paths a implementation choice not forced by the tooling. Which might need to be updated because a bug has been fixed.

For CRM 2016 (vanilla, 8.0) it's even worse. FakeXrmEasy.2016 requires the test project to use the 8.1.0.2 version of the dependencies. Which makes it that you are testing against a different CRM version then you might be writing your code for. This can't be fixed easily because the FakeXrmEasy 2016 code in intertwined with the Microsoft.CrmSdk.XrmTooling of 2016 Update 1 (the Crm Service Client interface is only implemented beginning with 8.1).

**Comment by jordimontana82** [comment]
Sounds sensible Michael.  Will look into this after the 365 London session :)

**Comment by jordimontana82** [comment]
HI Michael, 

I've updated the NuSpec files to now use version ranges so hopefully the community won't have to set the allowedVersions manually.

Will be pushing a version soon

**Comment by jordimontana82** [comment]
This should be fixed in the latest NuGet package now...

**Comment by fleep** [comment]
Making an additional note here: is there a particular reason it's locked to 3.2.0 rather than having a minimum version of 3.2.0? I'm having tests fail when compiling on other platforms when I don't use the latest FakeItEasy.

**Pull request closed without merging**
