### PR TITLE
Added test for query containing conditions in nested LinkEntity.

### PR DESCRIPTION
**Pull request by mike9182**
Nested conditions in LinkEntities are not evaluated.

### CODE REVIEW

**Comment by jordimontana82** [comment]
Thx! Will have a look

**Comment by mike9182** [comment]
I fixed this issue. After fixing the issue, I also needed to update an existing test which was expecting the wrong result.

**Comment by jordimontana82** [comment]
We were working on the same issue in parallel and sorted it out almost identically :)

**Comment by jordimontana82** [comment]
Gonna close this one and push a new version.

Thx for spotting this Michael!

**Pull request closed without merging**
