### PR TITLE
Added WinOpportunityRequestExecutor, LoseOpportunityRequestExecutor, QualifyLeadRequestExecutor and Tests.

### PR DESCRIPTION
**Pull request by Sejoslaw**
Hi @jordimontana82 

I added WinOpportunityRequestExecutor. It should work fine. 
Also I added few comments in code to give better undrstanding why I made something in the way I made it :)

P.S.
I was based on what You said in [this issue](https://github.com/jordimontana82/fake-xrm-easy/issues/192).

### CODE REVIEW

**Comment by jordimontana82** [comment]
Awesome!

I'll review this changes and merge them asap.

**Comment by Sejoslaw** [comment]
Hi @jordimontana82 

Sorry for trouble with multiple Executors but currently I have some time and also I need those so if You could check them and give me a feedback, it would be great :)

**Comment by jordimontana82** [comment]
Thx @Sejoslaw !

This one and #232 will be part of 1.35.0 soon...

**Comment by jordimontana82** [comment]
1.35.0 published now

**Pull request merged**
